spring.application.name=powerlifting-results-app
server.port=${SERVER_PORT:8080}
spring.mongodb.uri=${SPRING_MONGODB_URI}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB